#include <furi.h>
#include <gui/gui.h>
#include <gui/icon_i.h>
#include <gui/view_dispatcher.h>
#include <gui/scene_manager.h>
#include <gui/modules/menu.h>
#include <gui/modules/popup.h>

/* generated by fbt from .png files in images folder */
#include <ptt_icons.h>

typedef enum {
    PttAppScene_MainMenu,
    PttAppScene_FirstPopup,
    PttAppScene_SecondPopup,
    PttAppScene_count
} PttAppScene;

typedef enum { PttAppView_Menu, PttAppView_Popup } PttAppView;

typedef struct {
    SceneManager* scene_manager;
    ViewDispatcher* view_dispatcher;
    Menu* menu;
    Popup* popup;
} pttApp;

void test_app_view_dispatcher_init(pttApp* app) {
    app->view_dispatcher = view_dispatcher_alloc();
    view_dispatcher_enable_queue(app->view_dispatcher);

    app->menu = menu_alloc();
    app->popup = popup_alloc();

    view_dispatcher_set_event_callback_context(app->view_dispatcher, app);
    view_dispatcher_set_custom_event_callback(
        app->view_dispatcher, ptt_app_scene_manager_custom_event_callback);
    view_dispatcher_set_navigation_event_callback(
        app->view_dispatcher, test_app_scene_manager_navigation_event_callback);

    view_dispatcher_add_view(app->view_dispatcher, PttAppView_Menu, menu_get_view(app->menu));
    view_dispatcher_add_view(app->view_dispatcher, PttAppView_Popup, popup_get_view(app->popup));
}

void (*const ptt_app_scene_on_enter_handlers[])(void*) = {
    ptt_app_scene_on_enter_main_menu,
    ptt_app_scene_on_enter_popup_one,
    ptt_app_scene_on_enter_popup_two};

bool (*const ptt_app_scene_on_event_handlers[])(void*, SceneManagerEvent){
    ptt_app_scene_on_event_main_menu,
    ptt_app_scene_on_event_popup_one,
    ptt_app_scene_on_event_popup_two};

void (*const ptt_app_scene_on_exit_handlers[])(void*){
    ptt_app_scene_on_exit_main_menu,
    ptt_app_scene_on_exit_popup_one,
    ptt_app_scene_on_exit_popup_two};

const SceneManagerHandlers ptt_app_scene_event_handlers = {
    .on_enter_handlers = ptt_app_scene_on_enter_handlers,
    .on_event_handlers = ptt_app_scene_on_event_handlers,
    .on_exit_handlers = ptt_app_scene_on_exit_handlers,
    .scene_num = PttAppScene_count};

void ptt_app_scene_manager_init(pttApp* app) {
    app->scene_manager = scene_manager_alloc(&ptt_app_scene_event_handlers, app);
}

pttApp* ptt_init() {
    pttApp* app = malloc(sizeof(pttApp));
    ptt_app_scene_manager_init(app);
    ptt_app_view_dispatcher_init(app);
}

int32_t ptt_app(void* p) {
    UNUSED(p);
    FURI_LOG_I("TEST", "Hello world");
    FURI_LOG_I("TEST", "I'm ptt!");
    canvas_draw_frame() return 0;
}
