#include <furi.h>
#include <gui/gui.h>
#include <gui/icon_i.h>
#include <gui/view_dispatcher.h>
#include <gui/scene_manager.h>
#include <gui/modules/menu.h>
#include <gui/modules/popup.h>

/* generated by fbt from .png files in images folder */
#include <ptt_icons.h>

typedef enum {
    PttAppScene_MainMenu,
    PttAppScene_FirstPopup,
    PttAppScene_SecondPopup,
    PttAppScene_count
} PttAppScene;

typedef enum { PttAppEvent_ShowPopup1, PttAppEvent_ShowPopup2 } PttAppEvent;

typedef enum { PttAppMenuSelection_One, PttAppMenuSelection_Two } PttAppMenuSelection;

typedef enum { PttAppView_Menu, PttAppView_Popup } PttAppView;

typedef struct {
    SceneManager* scene_manager;
    ViewDispatcher* view_dispatcher;
    Menu* menu;
    Popup* popup;
} pttApp;

// Popup 1 Items

bool ptt_app_scene_on_event_popup_one(void* context, SceneManagerEvent event) {
    UNUSED(context);
    UNUSED(event);
    return false;
}

void ptt_app_scene_on_exit_popup_one(void* context) {
    pttApp* app = context;
    popup_reset(app->popup);
}

void ptt_app_scene_on_enter_popup_one(void* context) {
    pttApp* app = context;
    popup_reset(app->popup);
    popup_set_context(app->popup, app);
    popup_set_header(app->popup, "Popup 1", 64, 10, AlignCenter, AlignTop);
    popup_set_icon(app->popup, 10, 10, &I_one);
    popup_set_text(app->popup, "Popup numero uno!", 64, 20, AlignLeft, AlignTop);
    view_dispatcher_switch_to_view(app->view_dispatcher, PttAppView_Popup);
}

// End Popup 1 Items
// Popup 2 Items

bool ptt_app_scene_on_event_popup_two(void* context, SceneManagerEvent event) {
    UNUSED(context);
    UNUSED(event);
    return false;
}

void ptt_app_scene_on_exit_popup_two(void* context) {
    pttApp* app = context;
    popup_reset(app->popup);
}

void ptt_app_scene_on_enter_popup_two(void* context) {
    pttApp* app = context;
    popup_reset(app->popup);
    popup_set_context(app->popup, app);
    popup_set_header(app->popup, "Popup 2:", 64, 10, AlignCenter, AlignTop);
    popup_set_icon(app->popup, 10, 10, &I_two);
    popup_set_text(app->popup, "The second popup!!", 64, 20, AlignLeft, AlignTop);
    view_dispatcher_switch_to_view(app->view_dispatcher, PttAppView_Popup);
}

// End Popup 2 Items
// Main Menu Items

bool ptt_app_scene_manager_custom_event_callback(void* context, uint32_t event) {
    pttApp* app = context;
    return scene_manager_handle_custom_event(app->scene_manager, event);
}

bool ptt_app_scene_manager_navigation_event_callback(void* context) {
    pttApp* app = context;
    return scene_manager_handle_back_event(app->scene_manager);
}
void ptt_app_scene_on_exit_main_menu(void* context) {
    pttApp* app = context;
    menu_reset(app->menu);
}

bool ptt_app_scene_on_event_main_menu(void* context, SceneManagerEvent event) {
    pttApp* app = context;
    bool consumed = false;
    switch(event.type) {
    case SceneManagerEventTypeCustom:
        switch(event.event) {
        case PttAppEvent_ShowPopup1:
            scene_manager_next_scene(app->scene_manager, PttAppScene_FirstPopup);
            consumed = true;
            break;
        case PttAppEvent_ShowPopup2:
            scene_manager_next_scene(app->scene_manager, PttAppScene_SecondPopup);
            consumed = true;
            break;
        default:
            break;
        }
        break;
    default:
        consumed = false;
        break;
    }
    return consumed;
}

void ptt_app_menu_callback_main_menu(void* context, uint32_t index) {
    pttApp* app = context;
    switch(index) {
    case PttAppMenuSelection_One:
        scene_manager_handle_custom_event(app->scene_manager, PttAppEvent_ShowPopup1);
        break;
    case PttAppMenuSelection_Two:
        scene_manager_handle_custom_event(app->scene_manager, PttAppEvent_ShowPopup2);
        break;
    }
}

void ptt_app_scene_on_enter_main_menu(void* context) {
    pttApp* app = context;
    menu_reset(app->menu);

    menu_add_item(
        app->menu, "Popup 1", NULL, PttAppMenuSelection_One, ptt_app_menu_callback_main_menu, app);
    menu_add_item(
        app->menu, "Popup 2", NULL, PttAppMenuSelection_Two, ptt_app_menu_callback_main_menu, app);

    view_dispatcher_switch_to_view(app->view_dispatcher, PttAppView_Menu);
}

// End Main Menu Items

void ptt_app_view_dispatcher_init(pttApp* app) {
    app->view_dispatcher = view_dispatcher_alloc();
    view_dispatcher_enable_queue(app->view_dispatcher);

    app->menu = menu_alloc();
    app->popup = popup_alloc();

    view_dispatcher_set_event_callback_context(app->view_dispatcher, app);
    view_dispatcher_set_custom_event_callback(
        app->view_dispatcher, ptt_app_scene_manager_custom_event_callback);
    view_dispatcher_set_navigation_event_callback(
        app->view_dispatcher, ptt_app_scene_manager_navigation_event_callback);

    view_dispatcher_add_view(app->view_dispatcher, PttAppView_Menu, menu_get_view(app->menu));
    view_dispatcher_add_view(app->view_dispatcher, PttAppView_Popup, popup_get_view(app->popup));
}

void (*const ptt_app_scene_on_enter_handlers[])(void*) = {
    ptt_app_scene_on_enter_main_menu,
    ptt_app_scene_on_enter_popup_one,
    ptt_app_scene_on_enter_popup_two};

bool (*const ptt_app_scene_on_event_handlers[])(void*, SceneManagerEvent) = {
    ptt_app_scene_on_event_main_menu,
    ptt_app_scene_on_event_popup_one,
    ptt_app_scene_on_event_popup_two};

void (*const ptt_app_scene_on_exit_handlers[])(void*) = {
    ptt_app_scene_on_exit_main_menu,
    ptt_app_scene_on_exit_popup_one,
    ptt_app_scene_on_exit_popup_two};

const SceneManagerHandlers ptt_app_scene_event_handlers = {
    .on_enter_handlers = ptt_app_scene_on_enter_handlers,
    .on_event_handlers = ptt_app_scene_on_event_handlers,
    .on_exit_handlers = ptt_app_scene_on_exit_handlers,
    .scene_num = PttAppScene_count};

void ptt_app_scene_manager_init(pttApp* app) {
    app->scene_manager = scene_manager_alloc(&ptt_app_scene_event_handlers, app);
}

pttApp* ptt_init() {
    pttApp* app = malloc(sizeof(pttApp));
    ptt_app_scene_manager_init(app);
    ptt_app_view_dispatcher_init(app);
    return app;
}

void ptt_app_free(pttApp* app) {
    scene_manager_free(app->scene_manager);
    view_dispatcher_remove_view(app->view_dispatcher, PttAppView_Menu);
    view_dispatcher_remove_view(app->view_dispatcher, PttAppView_Popup);
    view_dispatcher_free(app->view_dispatcher);
    menu_free(app->menu);
    popup_free(app->popup);
    free(app);
}

int32_t ptt_app(void* p) {
    UNUSED(p);
    FURI_LOG_I("TEST", "Hello world");
    FURI_LOG_I("TEST", "I'm ptt!");
    pttApp* app = ptt_init();

    Gui* gui = furi_record_open(RECORD_GUI);
    view_dispatcher_attach_to_gui(app->view_dispatcher, gui, ViewDispatcherTypeFullscreen);
    scene_manager_next_scene(app->scene_manager, PttAppScene_MainMenu);
    view_dispatcher_run(app->view_dispatcher);

    furi_record_close(RECORD_GUI);
    ptt_app_free(app);
    return 0;
}
